image: archlinux
packages:
  - ruby
  - hugo
secrets:
  - 8d76aee2-cbf4-48ba-a5e8-05b2964b0150
  - eb6a2040-50fb-4b5b-b663-03cbc3f677f3
sources:
  - https://git.sr.ht/~michcioperz/hugoblog
tasks:
  - fix_timezone: |
      sudo timedatectl set-timezone Europe/Warsaw
  - deps: |
      gem install neocities
      mkdir ~/.config/neocities -p
  - build: |
      cd hugoblog
      hugo
  - deploy-pl: |
      cp ~/.pl-neocities-secret ~/.config/neocities/config
      cd hugoblog/public/pl
      $(ruby -e 'puts Gem.user_dir')/bin/neocities push .
  - deploy-en: |
      cp ~/.en-neocities-secret ~/.config/neocities/config
      cd hugoblog/public/en
      $(ruby -e 'puts Gem.user_dir')/bin/neocities push .


