title = "Michcioperz"
theme = "m14n"
enableRobotsTxt = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = true

[params]
  dateFormat = "2006-01-02"

[languages]
  [languages.en]
    languageName = "English"
    baseURL = "https://michcioperz.com"
    weight = 1
    [languages.en.params]
      description = "The website and the blog of Michał Sidor, a programmer"
  [languages.pl]
    languageName = "polski"
    baseURL = "https://ijestfajnie.pl"
    weight = 2
    [languages.pl.params]
      description = "Strona i blog programisty Michała Sidora"

