title = "Michcioperz"
theme = "m14n"
enableRobotsTxt = true
copyright = "Copyright © Michalina Sidor"

[outputs]
  page = ["HTML", "json"]
  section = ["HTML", "json", "RSS"]

[mediaTypes]
  [mediaTypes."application/activity+json"]
    suffixes = ["json"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = true

[params]
  dateFormat = "2006-01-02"

[author]
  name = "Michalina Sidor"

[languages]
  [languages.en]
    languageName = "English"
    baseURL = "https://michcioperz.com"
    weight = 1
    [languages.en.params]
      description = "The website and the blog of Michalina Sidor, a programmer"
  [languages.pl]
    languageName = "polski"
    baseURL = "https://ijestfajnie.pl"
    weight = 2
    [languages.pl.params]
      description = "Strona i blog programistki Michaliny Sidor"

